### ISSUE TITLE
UX -- Create color palette, and fonts -- index

### ISSUE THREAD

**Issue by Richardaeld** [alissatroiano/8-your-heart-out#34]
Create the color basis and select fonts to use for game body (index) page

**Comment by iama3191** [comment]
<img width="480" alt="Screen Shot 2022-02-25 at 13 08 04" src="https://user-images.githubusercontent.com/92436895/155712713-6e7ef2e2-2fa6-4278-b875-8e4a95b26aca.png">

Light theme:
<img width="312" alt="Screen Shot 2022-02-25 at 12 37 54" src="https://user-images.githubusercontent.com/92436895/155712942-af06b16c-ecff-4601-a968-6b732bc98824.png">

Dark theme:
<img width="305" alt="Screen Shot 2022-02-25 at 11 59 30" src="https://user-images.githubusercontent.com/92436895/155712971-dca97969-2fc4-4ad7-b4d3-e93dcfaa8d33.png">

**Comment by iama3191** [comment]
Fonts

font-family: 'Merriweather', serif;
